# Generated by Django 5.2 on 2025-04-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('first_surname', models.CharField(max_length=150, verbose_name='first surname')),
                ('last_surname', models.CharField(blank=True, max_length=150, null=True, verbose_name='last surname')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='department')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='position')),
                ('language', models.CharField(default='es', max_length=10, verbose_name='language')),
                ('timezone', models.CharField(default='America/Mexico_City', max_length=50, verbose_name='timezone')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('requires_password_reset', models.BooleanField(default=True, verbose_name='requires password reset')),
                ('password_changed', models.BooleanField(default=False, verbose_name='password changed')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last ip')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='last activity')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='idx_accounts_user_email'), models.Index(fields=['username'], name='idx_accounts_user_username')],
            },
        ),
    ]
