# Generated by Django 5.2 on 2025-04-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_token_blacklist',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='idx_core_token'), models.Index(fields=['created_at'], name='idx_core_token_created_at')],
            },
        ),
    ]
